In [1]:
import numpy as np
import pandas as pd

Вычисления с помощью Numpy

Задание 1

In [2]:
a = np.array([[1, 6],
              [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = np.mean(a, axis = 0)
mean_a


array([2. , 8.4])

Задание 2

In [5]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [6]:
at = a_centered.transpose()
at
a_centered_sp = np.dot(at[0],at[1])
a_centered_sp

8.0

In [7]:
a_centered_sp / 4

2.0

In [8]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

Работа с данными в Pandas

Задание 1

In [9]:
authors = pd.DataFrame({'author_id':[1,2,3], 'author_name':['Тургенев', 'Чехов', 'Островский']}, 
                       columns = ['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [10]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 
                                   'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price':[250,460,321,890,567,433,450]}, 
                    columns = ['author_id', 'book_title', 'price'])
book

author_id            book_title  price
0          1           Отцы и дети    250
1          1                 Рудин    460
2          1     Дворянское гнездо    321
3          2      Толстый и тонкий    890
4          2       Дама с собачкой    567
5          3                 Гроза    433
6          3  Таланты и поклонники    450

Задание 2

In [11]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    250
1          1    Тургенев                 Рудин    460
2          1    Тургенев     Дворянское гнездо    321
3          2       Чехов      Толстый и тонкий    890
4          2       Чехов       Дама с собачкой    567
5          3  Островский                 Гроза    433
6          3  Островский  Таланты и поклонники    450

Задание 3

In [12]:
top5 = authors_price.sort_values(by = 'price').tail()
top5.reset_index(drop = True, inplace = True)
top5

author_id author_name            book_title  price
0          3  Островский                 Гроза    433
1          3  Островский  Таланты и поклонники    450
2          1    Тургенев                 Рудин    460
3          2       Чехов       Дама с собачкой    567
4          2       Чехов      Толстый и тонкий    890

In [13]:
top5 = authors_price.nlargest(5,'price')
top5

author_id author_name            book_title  price
3          2       Чехов      Толстый и тонкий    890
4          2       Чехов       Дама с собачкой    567
1          1    Тургенев                 Рудин    460
6          3  Островский  Таланты и поклонники    450
5          3  Островский                 Гроза    433

Задание 4

In [26]:
authors_stat1 = pd.merge(authors_price.groupby('author_name')['price'].max(), 
                        authors_price.groupby('author_name')['price'].min(), on = 'author_name', how = 'inner')
authors_stat = pd.merge(authors_price.groupby('author_name')['price'].mean(), 
                        authors_stat1, on = 'author_name', how = 'inner')
authors_stat.rename(columns={'price': 'mean_price', 'price_x' : 'max_price', 'price_y' : 'min_price'}, inplace=True)
authors_stat


mean_price  max_price  min_price
author_name                                  
Островский   441.500000        450        433
Тургенев     343.666667        460        250
Чехов        728.500000        890        567

Задание 5

In [28]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    250  твердая
1          1    Тургенев                 Рудин    460   мягкая
2          1    Тургенев     Дворянское гнездо    321   мягкая
3          2       Чехов      Толстый и тонкий    890  твердая
4          2       Чехов       Дама с собачкой    567  твердая
5          3  Островский                 Гроза    433   мягкая
6          3  Островский  Таланты и поклонники    450   мягкая

In [41]:
book_info = pd.pivot_table(authors_price,
              index = ['author_name'],
              columns = ['cover'],
               values = ['price'],
               aggfunc = np.sum)
book_info.fillna(0,inplace = True)
book_info

price        
cover       мягкая твердая
author_name               
Островский   883.0     0.0
Тургенев     781.0   250.0
Чехов          0.0  1457.0

In [42]:
book_info.to_pickle('book_info.pkl')

In [44]:
book_info2 = pd.read_pickle('book_info.pkl')

In [45]:
book_info2

price        
cover       мягкая твердая
author_name               
Островский   883.0     0.0
Тургенев     781.0   250.0
Чехов          0.0  1457.0